### ISSUE TITLE
How to check table argument fields

### ISSUE THREAD

**Issue by cassava** [gvvaughan/typecheck#12]
Hi @gvvaughan,

First off, I really like this little library.

In my Lua library I have a lot of functions that accept a table full of fields
instead of accepting individual arguments. This is more readable than nameless arguments:
```lua
mylib.schedule {
  desc = "very much explaining",
  enable = true,
  id = "uuid",
  on = "event",
  run = function() end,
}
```
I was wondering whether the typecheck library directly supports checking these kind of arguments or how you would recommend checking the input table in an ergonomic way with typecheck.

**Comment by gvvaughan** [comment]
There isn't currently a straight forward way to do this with the current implementation -- currently everything would just be a `table` (or maybe a `table of string` if e.g. all arguments were string values).

Something like what is discussed in https://github.com/gvvaughan/typecheck/issues/4 would provide the API to give a name to specific table layout (names and value types for each 'argument'), and then you would be able to pass that name to the argscheck function for validation.  In your case it might be even nicer to go one step further and skip the naming step entirely by declaring the field names, valid value types and whether each is optional or not in the type check declaration string.  But there's no code to do any of that in the current release I'm afraid.

**Comment by cassava** [comment]
I'll move my thoughts to #4 then!
